apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.vault.name }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
{{- (.Files.Glob "secrets/vault/*").AsSecrets | nindent 2 }}